### ISSUE TITLE
wierd output

### ISSUE THREAD

**Issue by joelstahre** [bibz0r/cryptoBot#2]
Hi, i have the script running in crontab, but the outpu looks wierd:
```Last action was to buy (bought 1406 SC for 0.00000161 but the price is now at 1.63E-6)``` 
1.63E-6 ?

**Comment by codeandbattle** [comment]
This is scientific notation and needs to be changed to a floating number. I have this fixed on a local copy, and will be adding a pull request shortly.

**Comment by codeandbattle** [comment]
Fixed with newest [pull request](https://github.com/bibz0r/cryptoBot/pull/5).
