### ISSUE TITLE
How to run this

### ISSUE THREAD

**Issue by citizenking** [bibz0r/cryptoBot#4]
Hi, I am trying out your cryptobot. I get errors. I'm not a computer tech type but I need to know how i can create an html to run this program. I already have Xampp and Bracket software ready but need some guidance. Please get back to me as soon as you can. Thanks

**Comment by bibz0r** [comment]
> Hi, I am trying out your cryptobot. I get errors. I'm not a computer tech type but I need to know how i can create an html to run this program. I already have Xampp and Bracket software ready but need some guidance. Please get back to me as soon as you can. Thanks

Quite a bit late but better late than never:

Open up cmd, cd to your htdocs location (probably "cd C:\XAMPP\htdocs\cryptoBot") and then execute the bot "php bot.php"

Of course you should create a cronjob or some schedulded task that keeps running this script continously.
